# Generated by Django 3.1 on 2022-02-10 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_delete_subscription'),
        ('accounts', '0002_myuser_applied_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='active_promotions',
            field=models.ManyToManyField(to='checkout.Promotion'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_code', models.CharField(max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('auto_update', models.BooleanField(default=True)),
                ('extend', models.DateField(blank=True, help_text='Enter the date of purchase', null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.plan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
