# Generated by Django 3.1 on 2022-02-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220210_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
    ]
