# Generated by Django 3.1 on 2020-11-04 14:47

from django.db import migrations
from checkout.models import Plan

def plans_create(apps, schema_editor):
    Plan.objects.create(name='Bronze', price=10.0, period='1 week', code='J6A1Y46IY7', product_id='31913824')
    Plan.objects.create(name='Gold', price=15.0, period='2 week', code='KCWAUB77OJ', product_id='31914032')
    Plan.objects.create(name='Platinum', price=20.0, period='3 week', code='38389QJCRU', product_id='31914045')

class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion_fixed',
            old_name='price',
            new_name='coupon',
        ),
        migrations.RunPython(plans_create)
    ]
