# Generated by Django 3.1 on 2020-11-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion_fixed',
            old_name='price',
            new_name='coupon',
        ),
    ]
