# Generated by Django 3.1 on 2022-02-09 11:25

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_coupon_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='type',
        ),
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_day',
            field=models.DateField(blank=True, help_text='\n            Ending date. The date when you set the promotion to end. Is\n            NULL for promotions that you want active indefinitely.\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(default=checkout.models.allPlans, to='checkout.Plan'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_day',
            field=models.DateField(blank=True, help_text='\n            Starting date. The date when you set the promotion to start.\n            Is NULL for promotions that start immediately after they are\n            created.\n        ', null=True),
        ),
    ]
