# Generated by Django 3.1 on 2020-11-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20201104_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='promotion_fixed',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
