# Generated by Django 3.1 on 2022-02-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20220209_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='currency',
            field=models.CharField(default='USD', max_length=50, null=True),
        ),
    ]
