# Generated by Django 3.1 on 2022-02-09 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_promotion_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='promotion_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='coupon_type',
            field=models.CharField(blank=True, choices=[(0, 'Single'), (1, 'Multiple')], default=0, help_text='\n            SINGLE = one coupon code shared by all shoppers\n            MULTIPLE = array of unique coupon codes, each designed for individual use\n        ', max_length=15, null=True),
        ),
    ]
