# Generated by Django 3.1 on 2020-11-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20201104_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='coupon',
            new_name='value',
        ),
    ]
