# Generated by Django 3.1 on 2022-02-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20220209_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='promotion_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
