# Generated by Django 3.1 on 2020-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201104_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
