# Generated by Django 3.1 on 2020-11-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20201104_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
