# Generated by Django 3.1 on 2022-02-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20220209_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='trial',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='coupon_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Single'), (1, 'Multiple')], default=0, help_text='\n            SINGLE = one coupon code shared by all shoppers\n            MULTIPLE = array of unique coupon codes, each designed for individual use\n        ', null=True),
        ),
    ]
