# Generated by Django 3.1 on 2022-02-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20220210_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
