# Generated by Django 3.1 on 2020-11-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_promotion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='percent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
