# Generated by Django 3.1 on 2022-02-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20220210_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
