name: Trigger auto deployment for toiicheckout

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/toiicheckout-AutoDeployTrigger-3d2291fd-32c5-4861-bb54-233c35e39d4e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://registry-1.docker.io/
          username: ${{ secrets.TOIICHECKOUT_REGISTRY_USERNAME }}
          password: ${{ secrets.TOIICHECKOUT_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: https://registry-1.docker.io//toiicheckout:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TOIICHECKOUT_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n toiicheckout -g 2checkout_group --server https://registry-1.docker.io/ --username  ${{ secrets.TOIICHECKOUT_REGISTRY_USERNAME }} --password ${{ secrets.TOIICHECKOUT_REGISTRY_PASSWORD }}
            az containerapp update -n toiicheckout -g 2checkout_group --image https://registry-1.docker.io//toiicheckout:${{ github.sha }}
